// ---------------------------------------------------------------------------
// estate.mjs — Interactive Will Preparation (pure; runs on server and browser).
// Guided wizard data → a structured draft Will consistent with Indian
// conventions (Indian Succession Act, 1925): testator declaration, revocation
// clause, executor appointment, specific bequests, residuary clause, guardian
// nomination for minors, and a two-witness attestation block.
// The output is a DRAFT for review by a lawyer — registration is optional in
// India but attestation by two witnesses is mandatory.
// ---------------------------------------------------------------------------

export const WILL_STEPS = [
  { id: "testator", title: "Testator details", fields: ["fullName", "age", "pan", "address", "occupation"] },
  { id: "family", title: "Family & beneficiaries", fields: ["beneficiaries[]"] },
  { id: "assets", title: "Asset distribution", fields: ["assets[]"] },
  { id: "executor", title: "Executor", fields: ["executor", "alternateExecutor"] },
  { id: "guardian", title: "Guardianship (minors)", fields: ["guardian"] },
  { id: "special", title: "Special instructions", fields: ["residuaryBeneficiary", "specialInstructions"] },
  { id: "witnesses", title: "Witnesses", fields: ["witness1", "witness2"] },
];

const IN_DATE = () => new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });

export function generateDraft(d) {
  const b = (x) => (x || "________________");
  const beneList = (d.beneficiaries || []).map((x, i) => `${i + 1}. ${x.name} (${x.relation})`).join("\n");
  const assetClauses = (d.assets || []).map((a, i) => {
    const to = a.beneficiary || d.residuaryBeneficiary || "my residuary estate";
    return `${i + 1}. I bequeath my ${a.type?.toLowerCase() || "asset"} — ${a.description}${a.detail ? ` (${a.detail})` : ""} — absolutely to ${to}${a.sharePct && Number(a.sharePct) < 100 ? ` to the extent of ${a.sharePct}%` : ""}.`;
  }).join("\n\n");

  const minors = (d.beneficiaries || []).filter((x) => Number(x.age) > 0 && Number(x.age) < 18);
  const guardianClause = d.guardian?.name
    ? `GUARDIANSHIP\n\nIn the event of my death while any of my children ${minors.length ? `(${minors.map((m) => m.name).join(", ")}) ` : ""}remain minors, I appoint ${d.guardian.name} (${d.guardian.relation || "relation"}), residing at ${b(d.guardian.address)}, as their legal guardian, to care for their person and property until they attain majority.`
    : "";

  return `LAST WILL AND TESTAMENT

I, ${b(d.fullName)}, ${d.age ? `aged ${d.age} years, ` : ""}${d.occupation ? `${d.occupation}, ` : ""}holding PAN ${b(d.pan)}, residing at ${b(d.address)}, being of sound mind and disposing memory and free from any coercion or undue influence, do hereby declare this to be my LAST WILL AND TESTAMENT, made on this ${IN_DATE()}.

1. REVOCATION
I hereby revoke all former Wills, codicils and testamentary dispositions made by me at any time heretofore, and declare this to be my only valid Will.

2. FAMILY & BENEFICIARIES
The following persons are the beneficiaries under this Will:
${beneList || "________________"}

3. APPOINTMENT OF EXECUTOR
I appoint ${b(d.executor?.name)} (${d.executor?.relation || "relation"}), residing at ${b(d.executor?.address)}, as the sole Executor of this Will.${d.alternateExecutor?.name ? ` If ${d.executor?.name} is unable or unwilling to act, I appoint ${d.alternateExecutor.name} (${d.alternateExecutor.relation || "relation"}) as the alternate Executor.` : ""} My Executor shall pay my just debts, funeral expenses and taxes before distributing the estate.

4. SPECIFIC BEQUESTS
${assetClauses || "________________"}

5. RESIDUARY ESTATE
All the rest, residue and remainder of my estate — movable or immovable, present or future, wheresoever situated — not specifically bequeathed above, I give absolutely to ${b(d.residuaryBeneficiary)}.

${guardianClause ? guardianClause + "\n\n" : ""}${d.specialInstructions ? `SPECIAL INSTRUCTIONS\n\n${d.specialInstructions}\n\n` : ""}6. DECLARATION
I declare that I am executing this Will voluntarily, that I understand its contents, and that at the time of execution I am in sound health and disposing state of mind.

IN WITNESS WHEREOF, I have signed this Will on the date first written above at ${d.city || "________________"}.


_______________________
${b(d.fullName)} (Testator)

ATTESTATION
Signed by the above-named Testator as their Last Will in our joint presence, and attested by us in the presence of the Testator and of each other:

Witness 1: ${b(d.witness1?.name)}, ${b(d.witness1?.address)}    Signature: ____________
Witness 2: ${b(d.witness2?.name)}, ${b(d.witness2?.address)}    Signature: ____________

──────────────────────────────────────────────────────────────────────
DRAFT generated by myfinancial • ${IN_DATE()}
• Two independent witnesses (who are NOT beneficiaries) must attest the Will.
• Registration under the Registration Act, 1908 is optional but recommended.
• Nominations on bank/demat/insurance accounts do not override a Will —
  align them to avoid disputes.
• Have this draft reviewed by a qualified lawyer before execution.`;
}


/**
 * Estate-readiness checklist. Takes plain flags rather than reading a database,
 * so the same function serves the server and the browser-only vault.
 */
export function estateChecklist({ hasWill = false, vaultCategories = [], residency = "RESIDENT" } = {}) {
  const has = (c) => vaultCategories.includes(c);
  return [
    { item: "Will drafted", done: !!hasWill, why: "Without a Will, succession follows personal law (Hindu Succession Act / Indian Succession Act) — slower and possibly contrary to your wishes." },
    { item: "Will stored securely", done: has("WILL"), why: "Your executor must be able to locate the signed original." },
    { item: "Property deeds digitised", done: has("PROPERTY_DEEDS"), why: "Title chain documents speed up transmission and mutation." },
    { item: "Insurance policies digitised", done: has("INSURANCE_POLICIES"), why: "Claims need policy documents; keep nominee details current." },
    { item: "KYC / identity documents", done: has("KYC"), why: "Heirs need PAN/Aadhaar copies for transmission requests." },
    { item: "Nominations aligned with the Will", done: false, manual: true, why: "Bank, demat, mutual fund, EPF and insurance nominations should mirror the Will. A nomination does not override a Will, and a mismatch is the most common cause of family disputes." },
    ...(residency === "NRI" ? [{ item: "Cross-border estate advice", done: false, manual: true, why: "Assets in two countries may need situs-specific Wills, plus a forced-heirship and estate-tax review in your country of residence." }] : []),
  ];
}
